### ISSUE TITLE
Prepatch Errors

### ISSUE THREAD

**Issue by aurae-wow** [kemayo/wow-handynotes-legiontreasures#10]
Only running HandyNotes with this plugin just to make sure the errors weren't sneaking in from something else.

```
Message: ...AddOns/HandyNotes_LegionTreasures/handler/config.lua:602: attempt to call global 'GetPlayerAuraBySpellID' (a nil value)
Time: Wed Oct 26 23:27:25 2022
Count: 1
Stack: ...AddOns/HandyNotes_LegionTreasures/handler/config.lua:602: attempt to call global 'GetPlayerAuraBySpellID' (a nil value)
[string "@Interface/AddOns/HandyNotes_LegionTreasures/handler/config.lua"]:602: in function <...AddOns/HandyNotes_LegionTreasures/handler/config.lua:597>
[string "@Interface/AddOns/HandyNotes_LegionTreasures/handler/config.lua"]:614: in function `should_show_point'
[string "@Interface/AddOns/HandyNotes_LegionTreasures/handler/handler.lua"]:1102: in function `(for generator)'
[string "@Interface/AddOns/HandyNotes/HandyNotes.lua"]:443: in function <Interface/AddOns/HandyNotes/HandyNotes.lua:429>
[string "=[C]"]: ?
[string "@Interface/AddOns/HandyNotes/HandyNotes.lua"]:56: in function <Interface/AddOns/HandyNotes/HandyNotes.lua:51>
[string "@Interface/AddOns/HandyNotes/HandyNotes.lua"]:493: in function `?'
[string "@Interface/AddOns/HandyNotes/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:114: in function <...tes/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:114>
[string "=[C]"]: ?
[string "@Interface/AddOns/HandyNotes/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:24: in function <...tes/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Interface/AddOns/HandyNotes/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@Interface/AddOns/HandyNotes/Libs/HereBeDragons/HereBeDragons-2.0.lua"]:309: in function <.../HandyNotes/Libs/HereBeDragons/HereBeDragons-2.0.lua:292>
[string "@Interface/AddOns/HandyNotes/Libs/HereBeDragons/HereBeDragons-2.0.lua"]:339: in function <.../HandyNotes/Libs/HereBeDragons/HereBeDragons-2.0.lua:338>
```

```
Message: ...AddOns/HandyNotes_LegionTreasures/handler/config.lua:602: attempt to call global 'GetPlayerAuraBySpellID' (a nil value)
Time: Wed Oct 26 23:27:26 2022
Count: 1
Stack: ...AddOns/HandyNotes_LegionTreasures/handler/config.lua:602: attempt to call global 'GetPlayerAuraBySpellID' (a nil value)
[string "@Interface/AddOns/HandyNotes_LegionTreasures/handler/config.lua"]:602: in function <...AddOns/HandyNotes_LegionTreasures/handler/config.lua:597>
[string "@Interface/AddOns/HandyNotes_LegionTreasures/handler/config.lua"]:614: in function `should_show_point'
[string "@Interface/AddOns/HandyNotes_LegionTreasures/handler/handler.lua"]:1102: in function `(for generator)'
[string "@Interface/AddOns/HandyNotes/HandyNotes.lua"]:443: in function `UpdateMinimapPlugin'
[string "@Interface/AddOns/HandyNotes/HandyNotes.lua"]:502: in function `?'
[string "@Interface/AddOns/HandyNotes/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:114: in function <...tes/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:114>
[string "=[C]"]: ?
[string "@Interface/AddOns/HandyNotes/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:24: in function <...tes/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Interface/AddOns/HandyNotes/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:59: in function `SendMessage'
[string "@Interface/AddOns/HandyNotes_LegionTreasures/handler/handler.lua"]:1167: in function `Refresh'
[string "@Interface/AddOns/HandyNotes_LegionTreasures/handler/handler.lua"]:1163: in function <...ddOns/HandyNotes_LegionTreasures/handler/handler.lua:1158>
```

**Comment by kemayo** [comment]
Double-check that you've actually got the latest release? That should have been fixed by 6c5a24ba21cd7327d6f698bbacbb531ebb133caf which is in the v30 release I put out yesterday.

**Comment by aurae-wow** [comment]
It was v30, yes.  I deleted the addon and installed fresh to be sure everything was good as well, still the same two errors popping up.

**Comment by kemayo** [comment]
Drat, you're right. I've worked out what the problem is -- give me a second to fix it and do more releases.

**Comment by kemayo** [comment]
Okay, new release should fix it.
